<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>qASIC_Inspector</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\qASIC.Console\qASIC.Console.csproj" />
    <ProjectReference Include="..\qASIC.Core\qASIC.Core.csproj" />
  </ItemGroup>

</Project>
