<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\qASIC.Core\qASIC.Core.csproj" />
    <ProjectReference Include="..\qASIC.Console\qASIC.Console.csproj" />
    <ProjectReference Include="..\qASIC.Options\qASIC.Options.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
